### ISSUE TITLE
Cloudify compoer fails to import openstack types

### ISSUE THREAD

**Issue by thomnico** [cloudify-cosmo/cloudify-openstack-plugin#159] opened 2017-05-18 13:28 UTC
Cloudify composer can not import openstack types .. complaining that plugin can not be parsed.

Tried 2.0.1 and b3.1 without success

**Comment by idanmo** [comment] 2017-05-18 13:50
Hi,

The issue is caused by a duplicate description key in the plugin.yaml file.
A fix was already merged to `master` branch so you can try importing from `master`.

The next release of the plugin will include the fix.

**Comment by thomnico** [comment] 2017-05-19 08:02
Tried git pull from master .. zip and import ... same error : can not parse input

**Closed** 2019-04-01 14:07 UTC
